name: Push to Another Repository
on:
  push:
    branches:
      - develop
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  push-to-another-repo:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      # 소스코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
      
      # Node.js 설정 - cache 옵션 제거
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # cache 옵션 제거함
          
      # 의존성 설치
      - name: Install Dependencies
        run: |
          yarn install
          yarn cache clean  # 캐시 정리
        
      # 빌드
      - name: Build
        run: yarn build
        env:
          VITE_APP_BASE_URL: ${{ secrets.VITE_APP_BASE_URL }}

      # 다른 레포지토리로 푸시
      - name: Push Directory to Another Repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        with:
          source-directory: output
          destination-github-username: aaahyesu
          destination-repository-name: urdego_fe
          commit-message: 'fix: add push-to-another-repo'
          target-branch: main
          github-server: github.com
          user-email: ${{ secrets.JIRA_USER_EMAIL }}
          user-name: "GitHub Actions"